config/routes.rb
Rails.application.routes.draw do
  get "/my_products", to: "products#my_products", as: :my_products
  get "/my_sales", to: "products#my_sales", as: :my_sales
  get '/orders', to: 'orders#index', as: :orders
  devise_for :users
  root to: 'products#index'

  resources :products do
    resources :orders, only: [:new, :create]
    resources :cart_items, only: [:create]
  end
  resources :orders, only: [:edit, :show, :update, :destroy] do
    resources :reviews, only: [:new, :create]
    resources :payments, only: :new
  end
  resources :reviews, only: [:destroy]
  resources :carts, only: [:index, :update]

  get "/carts/:cart_id/payments/new", to: "payments#cart_payment", as: :new_cart_payment
  delete "cart_item/:id", to: "cart_items#destroy", as: :cart_item
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container-fluid footer-container py-5">
    <div class="row">
      <div class="col-12 flex-column">
        <p class="logo">Kampong Bakes</p>
        <div>
          <%= image_tag "instagram.svg", width: "24px" %>
          <p class="ml-2">@kampungbakes</p>
        </div>
        <div>
          <%= image_tag "mail.svg", width: "24px" %>
          <p class="ml-2">auyeongweibin@gmail.com</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-bg">
  <div class="inner-navbar">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "bread.png" %>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to carts_path, class: "ml-auto" do %>
        <%= image_tag "bag.png" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <% if current_user.userphoto.attached? %>
          <%= cl_image_tag current_user.userphoto.key, class: "avatar avatar-bordered" %>
        <% else %>
          <%= image_tag "default_profile_pic.jpg", alt: "Profile Pic", class: "avatar avatar-bordered" %>
        <% end %>
      </button>
    <% else %>
      <ul class="navbar-nav ml-auto d-inline-block">
        <li class="nav-item">
          <%= link_to carts_path, class: "ml-auto" do %>
            <%= image_tag "bag.png" %>
          <% end %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-orange" %>
          <%= link_to "Log In", new_user_session_path, class: "btn btn-pink" %>
        </li>
      </ul>
    <% end %>
    
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <% if current_user.seller %>
              <li class="nav-item"><%= link_to "Add a new product", new_product_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Your Products", my_products_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Your Sales", my_sales_path, class: "nav-link" %></li>
            <% end %>
            <li class="nav-item">
              <%= link_to "Your Orders", orders_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "Account details", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>