config/routes.rb
Rails.application.routes.draw do
  get "/my_products", to: "products#my_products", as: :my_products
  get "/my_sales", to: "products#my_sales", as: :my_sales
  get '/orders', to: 'orders#index', as: :orders
  devise_for :users
  root to: 'products#index'

  resources :products do
    resources :orders, only: [:new, :create]
    resources :cart_items, only: [:create]
  end
  resources :orders, only: [:edit, :show, :update, :destroy] do
    resources :reviews, only: [:new, :create]
    resources :payments, only: :new
  end
  resources :reviews, only: [:destroy]
  resources :carts, only: [:index, :update]

  get "/carts/:cart_id/payments/new", to: "payments#cart_payment", as: :new_cart_payment
  delete "cart_item/:id", to: "cart_items#destroy", as: :cart_item
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
  has_one :review, dependent: :destroy
  monetize :amount_cents

  validates :status, inclusion: { in: %w[pending paid accepted delivered] }
  validates :delivery, inclusion: { in: %w[delivery self-collection] }
  validates :product, :user, :quantity, :amount, :email, :contact, :name, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[new create]

  def index
    @orders = current_user.orders
    @products = policy_scope(Product).order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
    authorize @order
    redirect_to orders_path
  end

  def new
    @order = Order.new
    unless current_user.nil?
      @user = current_user
      @order.address = @user.address.to_s
      @order.email = @user.email
    end
    @order.quantity = 1
    @product = Product.find(params[:product_id])
    authorize @order
  end

  def create
    @order = Order.new(order_params)
    authorize @order
    @product = Product.find(params[:product_id])
    # if user not signed in
    if current_user.nil?
      new_user = User.new(email: params[:order][:email], password: params[:order][:contact], username: params[:order][:name])
      if new_user.save
        sign_in new_user
      else
        render :new
        return
      end
    end
    @order.user = current_user unless current_user.nil?
    @order.product = @product
    @order.status = "pending"
    @order.amount = @order.product.price
    if @order.save
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          name: @product.name,
          images: [@product.photo.key],
          amount: @product.price_cents,
          currency: 'sgd',
          quantity: @order.quantity
        }],
        success_url: order_url(@order),
        cancel_url: order_url(@order)
      )

      @order.update(checkout_session_id: session.id)
      redirect_to new_order_payment_path(@order)
    else
      render :new
    end
  end

  def edit
    authorize @order
  end

  def update
    authorize @order
    if @order.update(order_params)
      redirect_to my_sales_path
    else
      render :edit
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:status, :address, :quantity, :delivery, :name, :contact, :email)
  end
end

app/views/orders/_form.html.erb
<%= simple_form_for(order) do |f| %>
    <%= f.input :status, collection: %w[pending paid accepted delivered], as: :radio_buttons %>
    <%= f.submit class: "btn btn-orange"%>
  <% end %>

app/views/orders/edit.html.erb
<div class="sm-container">
  <%= link_to "< Back", my_sales_path, class: "btn-muted" %>
</div>
<div class="sm-container order-form">
  <h1>Update Order</h1>

  <%= render "form", order: @order %>
</div>

app/views/orders/index.html.erb
<div class="outer-container">
  <h1>My Orders</h1>
  <% @orders.each do |order| %>
    <div class="order-card">
      <%= cl_image_tag order.product.photo.key, height: 300, width: 400, crop: :fill, class: "product-img" %>
      <div class="card-content">
        <p class="card-title"><%= order.product.name %></p>
        <p>Quantity: <strong><%= order.quantity %></strong></p>
        <% if order.delivery == "delivery" %>
          <p>Delivery address: <strong><%= order.address %></strong></p>
        <% else %>
          <p>Self-collection address: <strong><%= order.product.user.address %></strong></p>
        <% end %>
        <p class="status">Status: <strong><%= order.status %></strong></p>
      <% if order.review %>
          <p>Review: <%= order.review.content %> ,<strong><%= order.review.rating %></strong> ★</p>
      <% end %>
      </div>
      <%= link_to "Add Review", new_order_review_path(order), class: "btn-orange m-2" %>
    </div>
  <% end %>
</div>

app/views/orders/new.html.erb
<div class="sm-container">
  <%= link_to "< Back", product_path(@product), class: "btn-muted" %>
</div>
<div class="sm-container mb-4">
  <div class="order-form">
    <h1>New Order</h1>
    <div class="order-product">
      <%= cl_image_tag @product.photo.key, alt: @product.name %>
      <div class="content">
        <p>Item: <strong><%= @product.name %></strong></p>
        <p>Price: <strong>$<%= @product.price %></strong></p>
      </div>
    </div>
    <h2>Order details</h2>
    <%= simple_form_for [@product, @order] do |f| %>
      <% if current_user.nil? %>
        <%= f.input :name, label: 'Name: ' %>
      <% else %>
        <%= f.input :name, label: 'Name: ', input_html: { value: current_user.username } %>
      <% end %>
      <%= f.input :contact, label: 'Phone Number: ', input_html: { type: 'tel' } %>
      <%= f.input :email, label: 'Email: ' %>
      <%= f.input :quantity, label: 'Quantity: ', input_html: { type: 'number' } %>
      <%= f.input :delivery, label: 'Delivery / Self Collect: ', as: :radio_buttons, collection: %w[delivery self-collection] %>
      <p id="self_collect_address">Self-collection Address: <strong><%= @product.user.address %></strong></p>
      <%= f.input :address, label: 'Delivery Address: ' %>
      <%= f.button :submit, 'Submit Order', class: "btn-orange" %>
    <% end %>
  </div>
</div>
<%= javascript_pack_tag 'delivery_display' %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>