config/routes.rb
Rails.application.routes.draw do
  get "/my_products", to: "products#my_products", as: :my_products
  get "/my_sales", to: "products#my_sales", as: :my_sales
  get '/orders', to: 'orders#index', as: :orders
  devise_for :users
  root to: 'products#index'

  resources :products do
    resources :orders, only: [:new, :create]
    resources :cart_items, only: [:create]
  end
  resources :orders, only: [:edit, :show, :update, :destroy] do
    resources :reviews, only: [:new, :create]
    resources :payments, only: :new
  end
  resources :reviews, only: [:destroy]
  resources :carts, only: [:index, :update]

  get "/carts/:cart_id/payments/new", to: "payments#cart_payment", as: :new_cart_payment
  delete "cart_item/:id", to: "cart_items#destroy", as: :cart_item
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  monetize :price_cents
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @cart_items = @cart.cart_items
    if user_signed_in?
      @cart.name = current_user.username
      @cart.email = current_user.email
      @cart.address = current_user.address
    end
    skip_policy_scope
  end

  def update
    authorize @cart

    unless user_signed_in?
      new_user = User.new(username: params[:cart][:name], email: params[:cart][:email], password: params[:cart][:contact])
      if new_user.save
        new_user.cart = @cart
        sign_in new_user
      else
        redirect_to carts_path, alert: "Email has already been taken"
        return
      end
    end

    @cart.update(cart_params)
    @cart.cart_items.each do |item|
      order = Order.new
      order.product = item.product
      order.user = @cart.user
      order.quantity = item.quantity
      order.delivery = @cart.delivery
      order.address = @cart.address
      order.amount = item.product.price
      order.status = "pending"
      order.name = @cart.name
      order.contact = @cart.contact
      order.email = @cart.email
      order.save!
    end

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: "Cart Items",
        amount: @cart.price_cents,
        currency: 'sgd',
        quantity: 1
      }],
      success_url: orders_url,
      cancel_url: carts_url
    )

    @cart.update(checkout_session_id: session.id)

    @cart.cart_items.destroy_all

    redirect_to new_cart_payment_path(@cart)
  end

  private

  def cart_params
    params.require(:cart).permit(:delivery, :address, :name, :contact, :email)
  end
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/index.html.erb
<div class="lg-container">
  <%= link_to "< View more products", root_path, class: "btn-muted" %>
</div>
<div class="outer-container">
  <h1>My Cart</h1>
  <% @cart_items.each do |item| %>
    <div class="order-card">
      <%= cl_image_tag item.product.photo.key, height: 300, width: 400, crop: :fill, class: "product-img" %>
      <div class="card-content">
        <p class="card-title"><%= item.product.name %></p>
        <p>Quantity: <strong><%= item.quantity %></strong></p>
        <p>Price: <%= item.product.price %></p>
      </div>
      <%= link_to cart_item_path(item.id), method: :delete do %>
        <%= image_tag "delete.png", class: "trash-btn" %>
      <% end %>
    </div>
  <% end %>
  
  <% unless @cart.cart_items.nil? || @cart.cart_items.empty? %>
      <button type="button" class="btn btn-orange" data-toggle="modal" data-target="#exampleModal">
        Checkout
      </button>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">My Cart</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= simple_form_for @cart do |f| %>
            <div class="modal-body">
              
                <%= f.input :name %>
                <%= f.input :email %>
                <%= f.input :contact %>
                <%= f.select :delivery, collection: %w[delivery self-collection] %>
                <%= f.input :address, label: "Delivery Address (leave N.A. if self-collecting)" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Confirm', class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  <% else %>
    <div class="order-card">
      <div class="mx-auto d-flex flex-column align-items-center">
      	<%= image_tag "missing.svg", class: "icon" %>
      	<h3 class="mx-auto">Cart is Empty</h3>
      </div>
    </div>
  <% end %>
  <h2 class="align-self-start d-inline-block">Total price: <%= @cart.price %></h2>
</div>

app/views/carts/show.html.erb
<div class="outer-container">
  <h1>My Cart</h1>
  <% @cart_items.each do |item| %>
    <div class="order-card">
      <%= cl_image_tag item.product.photo.key, height: 300, width: 400, crop: :fill, class: "product-img" %>
      <div class="card-content">
        <p class="card-title"><%= item.product.name %></p>
        <p>Quantity: <strong><%= item.quantity %></strong></p>
        <p>Price: <%= item.product.price %></p>
      </div>
      <%= link_to cart_item_path(item.id), method: :delete do %>
        <%= image_tag "delete.png", class: "trash-btn" %>
      <% end %>
    </div>
  <% end %>
  <h2 class="align-self-start d-inline-block">Total price: <%= @cart.price %></h2>
  <% unless @cart.cart_items.nil? || @cart.cart_items.empty? %>
      <button type="button" class="btn btn-pink ml-3" data-toggle="modal" data-target="#exampleModal">
        Checkout
      </button>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">My Cart</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= simple_form_for @cart do |f| %>
            <div class="modal-body">
              
                <%= f.select :delivery, collection: %w[delivery self-collection] %>
                <%= f.input :address, label: "Delivery Address (leave N.A. if self-collecting)" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Add to cart', class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>