config/routes.rb
Rails.application.routes.draw do
  get "/my_products", to: "products#my_products", as: :my_products
  get "/my_sales", to: "products#my_sales", as: :my_sales
  get '/orders', to: 'orders#index', as: :orders
  devise_for :users
  root to: 'products#index'

  resources :products do
    resources :orders, only: [:new, :create]
    resources :cart_items, only: [:create]
  end
  resources :orders, only: [:edit, :show, :update, :destroy] do
    resources :reviews, only: [:new, :create]
    resources :payments, only: :new
  end
  resources :reviews, only: [:destroy]
  resources :carts, only: [:index, :update]

  get "/carts/:cart_id/payments/new", to: "payments#cart_payment", as: :new_cart_payment
  delete "cart_item/:id", to: "cart_items#destroy", as: :cart_item
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :orders, dependent: :destroy # => product.orders
  has_many :reviews, through: :orders # => def #reviews Product.reviews
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :cart_items, dependent: :destroy
  has_rich_text :rich_body
  monetize :price_cents

  validates :name, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @products = Product.all
    @products = policy_scope(Product).order(created_at: :desc)
    @users = User.all

    # this returns active record relation of users with products
    @sellers = User.joins(:products).group('users.id')

    @markers = @sellers.geocoded.map do |seller|
      {
        lat: seller.latitude,
        lng: seller.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { seller: seller })
      }
    end

    if user_signed_in?
      @userloc = [
        {
          lat: current_user.latitude,
          lng: current_user.longitude
        }
      ]
    end
  end

  def new
    @product = Product.new
    skip_authorization
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    authorize @product
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @cart_item = CartItem.new
    skip_authorization
  end

  def edit
    authorize @product
  end

  def update
    authorize @product
    if @product.update(product_params)
      redirect_to product_path(@product.id)
    else
      render :edit
    end
  end

  def destroy
    authorize @product
    @product.destroy
    redirect_to root_path
  end

  def my_products
    @products = current_user.products
    skip_authorization
  end

  def my_sales
    @products = current_user.products
    skip_authorization
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :category, :photo, :rich_body)
  end
end

app/views/products/_form.html.erb
<%= simple_form_for(product) do |f| %>
    <%= f.input :name, label: "Title: " %>
    <label>Description: </label>
    <div class="form-inputs">
      <%= f.rich_text_area :rich_body %>
    </div>
    <%= f.input :price %>
    <%= f.input :category %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn btn-orange"%>
  <% end %>

app/views/products/_hero.html.erb
<div class="bg">
    <h1 class="hero-heading">Explore Singapore's best home-bakers</h1>
</div>

app/views/products/_info_window.html.erb
<h3><%= seller.username %></h3>
<h5 class="mb-3"><%= seller.address %></h5>
<div>
  <% seller.products.each do |product| %>
    <p>&nbsp;&nbsp;<%= product.name %></p>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="sm-container">
  <%= link_to "< Back", product_path(@product), class: "btn-muted" %>
</div>
<div class="sm-container order-form">
  <h1>Change Product Details</h1>

  <%= render "form", product: @product %>
</div>

app/views/products/index.html.erb
<%= render "hero" %>
<div class="outer-container section static">
  <div class="container-fluid">
    <h2 class="subheading">Featured Bakes</h2>
    <div class="row">
      <% @products.each do |product| %>
        <a href="<%= product_path(product) %>" class="col-12 col-md-6 col-lg-4">
          <div class="card-product">
            <div class="card-user">
                <%= user_avatar(product.user, "avatar") %>
                <p><%= product.user.username %></p>
            </div>

            <% if product.photo.attached? %>
              <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill, class: "product-photo" %>
            <% else %>
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/" class="product-photo" />
            <% end %>

            <div class="card-product-infos">
              <div class="card-description">
                <p class="card-title"><%= product.name %></p>
                <p class="card-address"><%= product.user.address %></p>
              </div>
              <div class="card-price">
                <p class="price"><%="#{humanized_money_with_symbol(product.price)}"%></p>
              </div>
            </div>
          </div>
      </a>
      <% end %>
    </div>
  </div>
  <h2 class="subheading">Find a home-baker near you</h2>
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-userloc="<%= @userloc.to_json unless @userloc.nil? %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/products/my_products.html.erb
<div class="outer-container">
    <div class="container-fluid text-center">
      <h1>My Products</h1>
      <div class="row">
        <% @products.each do |product| %>
          <a href="<%= product_path(product) %>" class="col-12 col-md-6 col-lg-4">
                    <div class="card-product">
                      <% if product.photo.attached? %>
                        <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill, class: "product-photo" %>
                      <% else %>
                        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="product-photo" />
                      <% end %>
                      <div class="card-product-infos">
                        <div class="card-description">
                          <p class="card-title"><%= product.name %></p>
                        </div>
                        <div class="card-price">
                          <p class="price"><%="$#{product.price}"%></p>
                        </div>
                      </div>
                    </div>
                </a>
        <% end %>
      </div>
    </div>
  </div>

app/views/products/my_sales.html.erb
<div class="outer-container">
  <h3>My Sales</h3>
    <% @products.each do |product| %>
      <% product.orders.each do |order| %>
        <div class="order-card">
          <% if order.nil? %>
            <p>Sorry, you have no orders!😔</p>
          <% end %>
          <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill, class: "product-img" %>
          <div class="card-content">
            <p class="card-title"><%= product.name %></p>
            <p>Quantity: <strong><%= order.quantity %></strong></p>
            <p>Delivery address: <strong><%= order.address %></strong></p>
            <p class="status">Status: <strong><%= order.status %></strong></p>
          </div>
          <%= link_to "Edit order", edit_order_path(order), class: "btn-orange edit-btn mr-3" %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/products/new.html.erb
<div class= "sm-container">
 <h2> Create new product</h2>

<%= render "form", product: @product %>
</div>

app/views/products/show.html.erb
<div class="lg-container">
  <%= link_to "< View more products", root_path, class: "btn-muted" %>
</div>

<div class="split-container">
  <div class="left-container">
    <% if @product.photo.attached? %>
      <%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
    <% end %>
  </div>
  <div class="right-container">
    <div class="card-product-infos">
      <p class="card-title"><h1><%= @product.name %></h1></p>
      <div class="card-price">
        <h4>$<%=@product.price%></h4>
      </div>
      <div class="address">
        <h3>Address</h3>
        <p class="card-address"><%= @product.user.address %></p>
      </div>
      <div class="description">
        <h3>Description</h3>
        <p class="card-description"><%= @product.rich_body %></p>
      </div>
      <div class="d-flex">
        <%= link_to "Order now", new_product_order_path(@product), class: "btn-orange" %>
        <button type="button" class="btn btn-pink ml-3" data-toggle="modal" data-target="#exampleModal">
          Add to Cart
        </button>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><%= @product.name %></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= simple_form_for [@product, @cart_item] do |f| %>
                <div class="modal-body">
                  
                    <%= f.input :quantity %>
                    <%= f.input :product_id, as: :hidden, input_html: {value: @product.id } %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <%= f.submit 'Add to cart', class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="lg-container">
  <% if policy(@product).edit? %>
    <%= link_to "Remove", product_path(@product), class: "btn btn-pink", method: :delete, data: { confirm: "Are you sure? All orders on this product will be destroyed." } %>
  <% end %>
  <% if policy(@product).destroy? %>
    <%= link_to "Edit", edit_product_path(@product), class: "btn btn-orange" %>
  <% end %>
</div>

<div class="outer-container">
  <h2 class="subheading">Reviews</h2>
  <% unless @product.reviews.empty? %>
    <% @product.reviews.each do |review| %>
      <div class="order-card p-3">
        <%= user_avatar(review.order.user, "avatar-large") %>
        
        <div class = "name">
          <strong><%= review.order.user.username %></strong>
          <div class = "stars-rating">
            <% (review.rating).times do |star| %>
              <i class="fas fa-star"></i>
            <% end %>
          </div>
          <div class = "review-content">
            <p><%= review.content %></p>
          </div>
        </div>
        <% if current_user == review.order.user %>
          <%= link_to review_path(review), class: "mr-3", method: :delete do %>
            <%= image_tag "delete.png", class: "trash-btn" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="order-card my-5">
      <div class="mx-auto d-flex flex-column align-items-center">
      	<%= image_tag "missing.svg", class: "icon" %>
      	<h3 class="mx-auto">No Reviews Yet</h3>
      </div>
    </div>
  <% end %>
</div>